--- Day 3: Lobby ---
You descend a short staircase, enter the surprisingly vast lobby, and are quickly cleared by the security checkpoint. When you get to the main elevators, however, you discover that each one has a red light above it: they're all offline.

"Sorry about that," an Elf apologizes as she tinkers with a nearby control panel. "Some kind of electrical surge seems to have fried them. I'll try to get them online soon."

You explain your need to get further underground. "Well, you could at least take the escalator down to the printing department, not that you'd get much further than that without the elevators working. That is, you could if the escalator weren't also offline."

"But, don't worry! It's not fried; it just needs power. Maybe you can get it running while I keep working on the elevators."



In [1]:
elf_data = []

with open('day03.txt', 'r') as file:
    for line in file:
        elf_data.append(line.strip())

print(len(elf_data))
print(elf_data[0:10])
print(type(elf_data))


200
['2235324222232244322422312234251333343425243363443152244111122632336242225745433452452451332445546443', '4342633549426242625533823432244459548433412443246235533216334436553544934221624474453562462242374424', '8434422643334243334243543423324744383442433444345133334323443723387546342444334386334543315426294343', '3314333333333253227333289433334173324336435282333332374344333346362333436223333531247332233332431333', '2432233222232224244344214455331424832252285224272831524326258455142222732648222482237235275222221622', '6456555534646565564173459654354446546674345456432576443336544564465623793536365563494844343586266956', '4922331489448743346893584377735442834632443434373231124434247962234578473993747531534353225262874382', '4329634636558644535534455549345256353469443795539452657625226416756735576575463654843527584644953254', '2454396282342313233436423353433434546123342334253853234273545734632444263222242142542533335242531345', '4635522634347741234563672633543582877478744697226363535745

There are batteries nearby that can supply emergency power to the escalator for just such an occasion. The batteries are each labeled with their joltage rating, a value from 1 to 9. You make a note of their joltage ratings (your puzzle input). For example:

987654321111111
811111111111119
234234234234278
818181911112111


In [2]:
test_data = ["987654321111111","811111111111119","234234234234278","818181911112111"]

The batteries are arranged into banks; each line of digits in your input corresponds to a single bank of batteries. Within each bank, you need to turn on exactly two batteries; the joltage that the bank produces is equal to the number formed by the digits on the batteries you've turned on. For example, if you have a bank like 12345 and you turn on batteries 2 and 4, the bank would produce 24 jolts. (You cannot rearrange batteries.)

You'll need to find the largest possible joltage each bank can produce. In the above example:

In 987654321111111, you can make the largest joltage possible, 98, by turning on the first two batteries.
In 811111111111119, you can make the largest joltage possible by turning on the batteries labeled 8 and 9, producing 89 jolts.
In 234234234234278, you can make 78 by turning on the last two batteries (marked 7 and 8).
In 818181911112111, the largest joltage you can produce is 92.
The total output joltage is the sum of the maximum joltage from each bank, so in this example, the total output joltage is 98 + 89 + 78 + 92 = 357.


In [50]:
def find_max_joltage(data):
    jolt = 0
    for d in data:
        jolt2 = joltage(d)
        jolt = jolt+jolt2
        print(jolt2, d)
    return jolt

def joltage(d):    
    d_list = list(d)
    d_list.sort(reverse=True)
    m = d_list[0]
    p = d.index(m)+1
    if p == len(d):
        m = d_list[1]
        m2 = max(d[d.index(m)+1:])
    else:
        m2 = max(d[p:])
    print(d, m, p, m2)
    return(int(m+m2))
        
        
print(find_max_joltage(test_data))

987654321111111 9 1 8
98 987654321111111
811111111111119 8 15 9
89 811111111111119
234234234234278 7 15 8
78 234234234234278
818181911112111 9 7 2
92 818181911112111
357



There are many batteries in front of you. Find the maximum joltage possible from each bank; what is the total output joltage?



In [51]:
print(find_max_joltage(elf_data))

2235324222232244322422312234251333343425243363443152244111122632336242225745433452452451332445546443 7 74 6
76 2235324222232244322422312234251333343425243363443152244111122632336242225745433452452451332445546443
4342633549426242625533823432244459548433412443246235533216334436553544934221624474453562462242374424 9 10 9
99 4342633549426242625533823432244459548433412443246235533216334436553544934221624474453562462242374424
8434422643334243334243543423324744383442433444345133334323443723387546342444334386334543315426294343 9 96 4
94 8434422643334243334243543423324744383442433444345133334323443723387546342444334386334543315426294343
3314333333333253227333289433334173324336435282333332374344333346362333436223333531247332233332431333 9 25 8
98 3314333333333253227333289433334173324336435282333332374344333346362333436223333531247332233332431333
2432233222232224244344214455331424832252285224272831524326258455142222732648222482237235275222221622 8 35 8
88 24322332222322242443442144553314248322522

--- Part Two ---
The escalator doesn't move. The Elf explains that it probably needs more joltage to overcome the static friction of the system and hits the big red "joltage limit safety override" button. You lose count of the number of times she needs to confirm "yes, I'm sure" and decorate the lobby a bit while you wait.

Now, you need to make the largest joltage by turning on exactly twelve batteries within each bank.

The joltage output for the bank is still the number formed by the digits of the batteries you've turned on; the only difference is that now there will be 12 digits in each bank's joltage output instead of two.

Consider again the example from before:

987654321111111
811111111111119
234234234234278
818181911112111
Now, the joltages are much larger:

In 987654321111111, the largest joltage can be found by turning on everything except some 1s at the end to produce 987654321111.
In the digit sequence 811111111111119, the largest joltage can be found by turning on everything except some 1s, producing 811111111119.
In 234234234234278, the largest joltage can be found by turning on everything except a 2 battery, a 3 battery, and another 2 battery near the start to produce 434234234278.
In 818181911112111, the joltage 888911112111 is produced by turning on everything except some 1s near the front.
The total output joltage is now much larger: 987654321111 + 811111111119 + 434234234278 + 888911112111 = 3121910778619.



What is the new total output joltage?